name : first workflow 
on:
  push:
    branches:
      - feature/basic-workflow

jobs:
  do-things:
    name: do stff
    runs-on: ubuntu-latest
    steps:
      - name: i will echo ur name 
        run: echo "hello my little frind"
      - name: i will do an error 
        run: echo "hello i will do error now"
        run: exit 1
