name: continous integration and continous delivery for go proje
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - mian

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: continous integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: golang_app
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: path setup for caching 
        id: go-paths
        working-directory: ${{ github.workspace }}
        run: |
          echo " ${{ github.workspace }}"
          echo " gomodcache = $(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo " gocache = $(go env GOCACHE)" >> $GITHUB_OUTPUT
          cat "${GITHUB_OUTPUT}"
      - name: clone 
        uses: actions/checkout@v3.1.0
      - name: debug
        run : |
          echo "Go version: $(go version)"
          echo "GOMODCACHE: $(go env GOMODCACHE || echo 'Not set')"
          echo "GOCACHE: $(go env GOCACHE || echo 'Not set')"
          echo " ${{ steps.go-paths.outputs.gomodcache }}"
          echo " ${steps.go-paths.outputs.gocache}"

      - name: caching 
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-paths.outputs.gomodcache }}
            ${{ steps.go-paths.outputs.gocache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: get dep
        env:
          CONTEXT_ITEM: ${{ toJson(steps) }}
        run: |
          go get app
          echo "this is the context item ${CONTEXT_ITEM}"
      - name: building 
        run: go build
      - name: run linting 
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: golang_app
      - name: run tests
        run: go test   
      - name: uploading artifact 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event_name }}-${{ github.run_id }}-${{ github.run_attempt }}-golang_app
          path: golang_app/app