name: continous integration and continous delivery for go proje
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: continous integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: golang_app
    steps:
      - name: path setup for caching 
        working-directory: ${{ github.workspace }}
        run: |
          echo " ${{ github.workspace }}"
          echo " gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo " gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
      - name: clone 
        uses: actions/checkout@v3.1.0
      - name: caching 
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.path-setup.outputs.gomodcache }}
            ${{ steps.path-setup.outputs.gocache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: get dep
        run: |
          go get app
          echo " toJson(steps)" 
      - name: building 
        run: go build
      - name: run linting 
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: golang_app
      - name: run tests
        run: go test   
      - name: uploading artifact 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event_name }}-${{ github.run_id }}-${{ github.run_attempt }}-golang_app
          path: golang_app/app