name: Using Defaults 
on:
  push:
    branches:
      - feature/defaults

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Create Source Dir
        run: mkdir src
        shell: bash
      - name: Use Python 
        run: import os; print("Hi iam running Pythonnnnnnnnnnn!"+os.getcwd())
        shell: python
        working-directory: src
      - name: Use Bash
        env: MYVAR= $(pwd)
        run: echo "I'm running hum-drum bash in ${MYVAR}. Booo."
        shell: bash
        working-directory: src
      - name: Use Bash Also
        run: echo "I'm running bash also, but elsewhere in $(pwd). Booo."
        shell: bash
  second-job:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Create Source Directory
        run: mkdir src
        shell: bash
      - name: Use Bash
        run: echo "I'm running bash in $(pwd). So sad."
        shell: bash
        working-directory: src