name: issues workflow
on:
  issues:
    types: [opened]

jobs:
  playing-with-issues:
    name: play with issues
    runs-on: ubuntu-latest
    steps:
      - name: priting isssue info
        env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
        run: echo " the action is ${{ github.event.action }} and the event name is ${{ github.event_name }}"
