name: manul workflow
on:
  workflow_dispatch:
    inputs:
      choice-example :
        description: 'choise an example'
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug
      string-example:
        description: 'string example'
        required: true
        default: input
        type: string
  # push:
  #   branches:
  #     - main
jobs:
  do-things:
    name: do things 
    runs-on: ubuntu-latest
    steps:
      - name: do a thing
        run: echo "I've done a thing manually with ${{ github.event.inputs.choice-example }} and ${{ github.event.inputs.string-example }}!"

# curl -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer <TOKEN>" \
#   https://api.github.com/repos/Mustafaibra/github-actions-practices/actions/workflows/manual.yaml/dispatches \
#   -d '{
#     "ref": "main",
#     "inputs": {
#       "choice-example": "warning",
#       "string-example": "input"
#     }
#   }'