name: using reusable workflows
on:
  push:
    branches:
      - feature 

jobs:
  centralized-job:
    uses: ./.github/workflows/reusable.yaml
    with:
      string-example: sasa
      choice-example: debug