name: using actions
on:
  push:
    branches:
      - feature/using-actions

jobs:
  do-things:
    name: doing action things 
    runs-on: ubuntu-latest
    steps:
      - name: list dir content
        run: ls -latr
      - name: check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true
      - name: list dir again
        run: ls -latr
      - name: Use GitHub Script Action
        uses: actions/github-script@v6
        with:
          script: |
            const create = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Learning To Use Script-Actions!",
              body: "Hey, we used script actions! Here's the commit SHA that triggered this: ${{github.sha}}"
            })
            return create.data.number